#!/bin/bash -ex

function write_to_setup() {
  local file=$1; shift
  local urlbase=$1; shift

  local dest=/setup/$file

  [[ -f $dest ]] && return 0

  local url=$urlbase/$file
  curl -l $url > $dest || return 6
}

ROOT_PASS=$1; shift

source /root/.bash_profile

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
export DEBCONF_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

echo "Executing chroot mods for base image"

# we do this for convenience b/c these are often ephemeral containers without other user accounts
echo "root:$ROOT_PASS" | chpasswd

sed -i 's/#Storage=auto/Storage=volatile/g' /etc/systemd/journald.conf

rm -f /etc/systemd/system/multi-user.target.wants/machines.target
rm -f /etc/systemd/system/timers.target.wants/fstrim.timer

# rely on this update operation here
apt-get update && apt-get install -y curl locales

# read env
[[ -f "/setup/chroot-dl-versions.env" ]] && source /setup/chroot-dl-versions.env
TO_CACHE=("$JDK_PKG")

for p in "${TO_CACHE[@]}"; do
  apt-get -d install -y $p
done

echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen

local_cache_url='http://10.109.39.196:9010'

# TODO: check for matching sha sum
write_to_setup $local_cache_url "hadoop-$HADOOP_VER.tar.gz" ||  ((echo "Unable to fetch Hadoop distribution" >&2) && exit 1) &
write_to_setup $local_cache_url "hbase-$HBASE_VER.tar.gz" ||  ((echo "Unable to fetch HBase distribution" >&2) && exit 1) &
write_to_setup $local_cache_url "kafka_$KAFKA_VER.tgz" ||  ((echo "Unable to fetch Kafka distribution" >&2) && exit 1) &
write_to_setup $local_cache_url "apache-zookeeper-$ZOOKEEPER_VER-bin.tar.gz" ||  ((echo "Unable to fetch Zookeeper distribution" >&2) && exit 1) &
