#!/bin/bash -ex

ROOT_PASS=$1; shift

echo "Executing chroot mods for base image"

source /root/.bash_profile

# we do this for convenience b/c these are often ephemeral containers without other user accounts
echo "root:$ROOT_PASS" | chpasswd

sed -i 's/#Storage=auto/Storage=volatile/g' /etc/systemd/journald.conf

rm -f /etc/systemd/system/multi-user.target.wants/machines.target
rm -f /etc/systemd/system/timers.target.wants/fstrim.timer
